#!/bin/bash

declare -a arr=(
    "cloud.google.com/go"
	"cloud.google.com/go/storage"
	"github.com/GoogleCloudPlatform/cloudsql-proxy"
	"github.com/apparentlymart/go-cidr"
	"github.com/asaskevich/govalidator"
	"github.com/aws/aws-sdk-go"
	"github.com/bmatcuk/doublestar"
	"github.com/cenkalti/backoff"
	"github.com/charlievieth/fs"
	"github.com/cloudfoundry/bosh-cli"
	"github.com/cloudfoundry/bosh-utils"
	"github.com/cppforlife/go-patch"
	"github.com/fatih/color"
	"github.com/ghodss/yaml"
	"github.com/imdario/mergo"
	"github.com/lib/pq"
	"github.com/mattn/go-colorable"
	"github.com/mattn/go-isatty"
	"github.com/maxbrunsfeld/counterfeiter/v6"
	"github.com/miekg/dns"
	"github.com/nu7hatch/gouuid"
	"github.com/onsi/ginkgo" 
	"github.com/onsi/gomega" 
	"github.com/square/certstrap" 
	"github.com/stretchr/testify" 
	"github.com/tjarratt/gcounterfeiter"
	"github.com/go-acme/lego/v4" 
	"golang.org/x/crypto"
	"golang.org/x/net"
	"golang.org/x/oauth2" 
	"google.golang.org/api" 
	"gopkg.in/square/go-jose.v2" 
	"gopkg.in/urfave/cli.v1"
	"gopkg.in/yaml.v2" 
)

for i in "${arr[@]}"
do
    go get -u "$i"
done