---
azs:
- name: z1
  cloud_properties:
    availability_zone: {{ .AvailabilityZone }}

vm_types:
- name: concourse-web-small
  cloud_properties:
    instance_type: t3.small
    ephemeral_disk:
      size: 20_000
      type: gp2
      encrypted: true
    security_groups:
    - {{ .VMsSecurityGroupID }}

- name: concourse-web-medium
  cloud_properties:
    instance_type: t3.medium
    ephemeral_disk:
      size: 20_000
      type: gp2
      encrypted: true
    security_groups:
    - {{ .VMsSecurityGroupID }}

- name: concourse-web-large
  cloud_properties:
    instance_type: t3.large
    ephemeral_disk:
      size: 20_000
      type: gp2
      encrypted: true
    security_groups:
    - {{ .VMsSecurityGroupID }}

- name: concourse-web-xlarge
  cloud_properties:
    instance_type: t3.xlarge
    ephemeral_disk:
      size: 20_000
      type: gp2
      encrypted: true
    security_groups:
    - {{ .VMsSecurityGroupID }}

- name: concourse-web-2xlarge
  cloud_properties:
    instance_type: t3.2xlarge
    ephemeral_disk:
      size: 20_000
      type: gp2
      encrypted: true
    security_groups:
    - {{ .VMsSecurityGroupID }}

# on-demand prices for eu-west-2 region
# this is roughly a middle ground of pricing
# across regions and is also where EB is
# we set spot bid to on-demand * 1.2

- name: concourse-medium
  cloud_properties:
    instance_type: t3.medium {{ if .Spot }}
    spot_bid_price: 0.0567 # on-demand price: 0.0472
    spot_ondemand_fallback: true # {{ end }}
    ephemeral_disk:
      size: 200_000
      type: gp2
      encrypted: true
    security_groups:
    - {{ .VMsSecurityGroupID }}

- name: concourse-large
  cloud_properties: {{ if eq .WorkerType "m5" }}
    instance_type: m5.large {{ if .Spot }}
    spot_bid_price: 0.133 # on-demand price: 0.111
    spot_ondemand_fallback: true # {{ end }} {{else if eq .WorkerType "m5a" }}
    instance_type: m5a.large {{ if .Spot }}
    spot_bid_price: 0.120 # on-demand price: 0.100
    spot_ondemand_fallback: true # {{ end }} {{ else }}
    instance_type: m4.large {{ if .Spot }}
    spot_bid_price: 0.139 # on-demand price: 0.116
    spot_ondemand_fallback: true # {{ end }} {{ end }}
    ephemeral_disk:
      size: 200_000
      type: gp2
      encrypted: true
    security_groups:
    - {{ .VMsSecurityGroupID }}

- name: concourse-xlarge
  cloud_properties: {{ if eq .WorkerType "m5" }}
    instance_type: m5.xlarge {{ if .Spot }}
    spot_bid_price: 0.266 # on-demand price: 0.222
    spot_ondemand_fallback: true # {{ end }} {{else if eq .WorkerType "m5a" }}
    instance_type: m5a.xlarge {{ if .Spot }}
    spot_bid_price: 0.240 # on-demand price: 0.200
    spot_ondemand_fallback: true # {{ end }} {{ else }}
    instance_type: m4.xlarge {{ if .Spot }}
    spot_bid_price: 0.278 # on-demand price: 0.232
    spot_ondemand_fallback: true # {{ end }} {{ end }}
    ephemeral_disk:
      size: 200_000
      type: gp2
      encrypted: true
    security_groups:
    - {{ .VMsSecurityGroupID }}

- name: concourse-2xlarge
  cloud_properties: {{ if eq .WorkerType "m5" }}
    instance_type: m5.2xlarge {{ if .Spot }}
    spot_bid_price: 0.533 # on-demand price: 0.444
    spot_ondemand_fallback: true # {{ end }} {{else if eq .WorkerType "m5a" }}
    instance_type: m5a.2xlarge {{ if .Spot }}
    spot_bid_price: 0.480 # on-demand price: 0.400
    spot_ondemand_fallback: true # {{ end }} {{ else }}
    instance_type: m4.2xlarge {{ if .Spot }}
    spot_bid_price: 0.557 # on-demand price: 0.464
    spot_ondemand_fallback: true # {{ end }} {{ end }}
    ephemeral_disk:
      size: 200_000
      type: gp2
      encrypted: true
    security_groups:
    - {{ .VMsSecurityGroupID }}

- name: concourse-4xlarge
  cloud_properties: {{ if eq .WorkerType "m5" }}
    instance_type: m5.4xlarge {{ if .Spot }}
    spot_bid_price: 1.066 # on-demand price: 0.888
    spot_ondemand_fallback: true # {{ end }} {{else if eq .WorkerType "m5a" }}
    instance_type: m5a.4xlarge {{ if .Spot }}
    spot_bid_price: 0.960 # on-demand price: 0.800
    spot_ondemand_fallback: true # {{ end }} {{ else }}
    instance_type: m4.4xlarge {{ if .Spot }}
    spot_bid_price: 1.114 # on-demand price: 0.928
    spot_ondemand_fallback: true # {{ end }} {{ end }}
    ephemeral_disk:
      size: 200_000
      type: gp2
      encrypted: true
    security_groups:
    - {{ .VMsSecurityGroupID }}

- name: concourse-10xlarge
  cloud_properties:
    instance_type: m4.10xlarge {{ if .Spot }}
    spot_bid_price: 2.784 # on-demand price: 2.32
    spot_ondemand_fallback: true # {{ end }}
    ephemeral_disk:
      size: 200_000
      type: gp2
      encrypted: true
    security_groups:
    - {{ .VMsSecurityGroupID }}

- name: concourse-12xlarge
  cloud_properties: {{ if eq .WorkerType "m5" }}
    instance_type: m5.12xlarge {{ if .Spot }}
    spot_bid_price: 3.197 # on-demand price: 2.664
    spot_ondemand_fallback: true # {{ end }} {{ else }}
    instance_type: m5a.12xlarge {{ if .Spot }}
    spot_bid_price: 2.880 # on-demand price: 2.400
    spot_ondemand_fallback: true # {{ end }} {{ end }}
    ephemeral_disk:
      size: 200_000
      type: gp2
      encrypted: true
    security_groups:
    - {{ .VMsSecurityGroupID }}

- name: concourse-16xlarge
  cloud_properties:
    instance_type: m4.16xlarge {{ if .Spot }}
    spot_bid_price: 4.454 # on-demand price: 3.712
    spot_ondemand_fallback: true # {{ end }}
    ephemeral_disk:
      size: 200_000
      type: gp2
      encrypted: true
    security_groups:
    - {{ .VMsSecurityGroupID }}

- name: concourse-24xlarge
  cloud_properties: {{ if eq .WorkerType "m5" }}
    instance_type: m5.24xlarge {{ if .Spot }}
    spot_bid_price: 6.394 # on-demand price: 5.328
    spot_ondemand_fallback: true # {{ end }} {{ else }}
    instance_type: m5a.24xlarge {{ if .Spot }}
    spot_bid_price: 5.760 # on-demand price: 4.800
    spot_ondemand_fallback: true # {{ end }} {{ end }}
    ephemeral_disk:
      size: 200_000
      type: gp2
      encrypted: true
    security_groups:
    - {{ .VMsSecurityGroupID }}

- name: compilation
  cloud_properties: {{ if eq .WorkerType "m5" }}
    instance_type: m5.large {{ if .Spot }}
    spot_bid_price: 0.133 # on-demand price: 0.111
    spot_ondemand_fallback: true # {{ end }} {{else if eq .WorkerType "m5a" }}
    instance_type: m5a.large {{ if .Spot }}
    spot_bid_price: 0.120 # on-demand price: 0.100
    spot_ondemand_fallback: true # {{ end }} {{ else }}
    instance_type: m4.large {{ if .Spot }}
    spot_bid_price: 0.139 # on-demand price: 0.116
    spot_ondemand_fallback: true # {{ end }} {{ end }}

disk_types:
- name: default
  disk_size: 50_000
  cloud_properties:
    type: gp2
    encrypted: true
- name: large
  disk_size: 200_000
  cloud_properties:
    type: gp2
    encrypted: true

networks:
- name: public
  type: manual
  subnets:
  - range: {{ .PublicCIDR }}
    gateway: {{ .PublicCIDRGateway }}
    az: z1
    static: {{ .PublicCIDRStatic }}
    reserved: {{ .PublicCIDRReserved }}
    cloud_properties:
      subnet: {{ .PublicSubnetID }}
- name: private
  type: manual
  subnets:
  - range: {{ .PrivateCIDR }}
    gateway: {{ .PrivateCIDRGateway }}
    az: z1
    reserved: {{ .PrivateCIDRReserved }}
    cloud_properties:
      subnet: {{ .PrivateSubnetID }}
- name: vip
  type: vip


vm_extensions:
- name: atc
  cloud_properties:
    security_groups:
    - {{ .VMsSecurityGroupID }}
    - {{ .ATCSecurityGroupID }}

compilation:
  workers: 5
  reuse_compilation_vms: true
  az: z1
  vm_type: compilation
  network: private
