---
platform: linux

params:
  GOOS: darwin
  GOARCH:
  OUTPUT_FILE:

inputs:
- name: control-tower
- name: control-tower-ops

outputs:
- name: build-darwin-amd64

run:
  path: control-tower/ci/tasks/build.sh
