---
platform: linux

params:
  GOOS: linux
  GOARCH:
  OUTPUT_FILE:

inputs:
- name: control-tower
- name: control-tower-ops

outputs:
- name: build-linux

run:
  path: control-tower/ci/tasks/build.sh
