---
platform: linux

params:
  GOOS:
  GOARCH:
  OUTPUT_FILE:

inputs:
- name: control-tower
- name: control-tower-ops
- name: version

outputs:
- name: build-linux-amd64

run:
  path: control-tower/ci/tasks/build.sh
