---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: engineerbetter/pcf-ops
    tag: latest

inputs:
- name: control-tower
- name: binary-linux

run:
  path: control-tower/ci/tasks/cleanup-tests.rb

params:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  GOOGLE_APPLICATION_CREDENTIALS_CONTENTS:
  IAAS:
  VERBOSE: true
