platform: linux

inputs:
- name: control-tower-ops
- name: control-tower
- name: build-metadata

outputs:
- name: ops-version

params:
  CONCOURSE_PASSWORD:
  CONCOURSE_URL:

run:
  path: control-tower/ci/tasks/get-ops-version.sh
