---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: engineerbetter/pcf-ops
    tag: latest
inputs:
- name: control-tower
- name: binary-linux

run:
  path: control-tower/ci/tasks/system-test-options-and-destroy.sh

params:
  IAAS:
  GOOGLE_APPLICATION_CREDENTIALS_CONTENTS:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  BINARY_PATH:
  BITBUCKET_AUTH_CLIENT_ID:
  BITBUCKET_AUTH_CLIENT_SECRET:
  GITHUB_AUTH_CLIENT_ID:
  GITHUB_AUTH_CLIENT_SECRET:
  MICROSOFT_AUTH_CLIENT_ID:
  MICROSOFT_AUTH_CLIENT_SECRET:
  MICROSOFT_AUTH_TENANT:
  EB_WILDCARD_CERT:
  EB_WILDCARD_KEY:
  VERBOSE:
